### ISSUE TITLE
Incorrect schema at BuildAndDeployment/Build.yaml

### ISSUE THREAD

**Issue by BlancLoup** [devsecopsmaturitymodel/DevSecOps-MaturityModel-data#19]
[BuildAndDeployment/Build.yaml#L81](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel-data/blob/d6e57cb60fcc8a8146dc7446f1e4368ce98c4d6c/src/assets/YAML/default/BuildAndDeployment/Build.yaml#L81)

- `Build.yaml` uses property 'comment' only once for entity `Pinning of artifacts` and it's property isn't defined at yaml-schema.
- `Description` property is missing which is not schema-compliant

Better refactoring is replacing `comment` with `description` and adding "A patch policy is defined" as `dependsOn` item.
```yaml
    Pinning of artifacts:
      uuid: f3c4971e-9f4d-4e59-8ed0-f0bdb6262477
      description:
        The usage of pinning requires a good processes for patching. Therefore,
        choose this activity wisely.
      dependsOn:
        - Defined build process
        - A patch policy is defined
      ...
```
